config/routes.rb
Rails.application.routes.draw do

    devise_for :profs, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'profs/omniauth_callbacks'}
    #devise_for :technicals, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'technicals/omniauth_callbacks'}

    scope '(:locale)' do

      devise_for :profs, skip: :omniauth_callbacks, controllers: {
        registrations: 'profs/registrations',
        confirmations: 'profs/confirmations',
      }

      devise_for :technicals, controllers: {
        registrations: 'technicals/registrations',
        confirmations: 'technicals/confirmations',
        sessions: 'technicals/sessions',
      }

      devise_for :admins, controllers: {
        registrations: 'admins/registrations'
      }

      namespace :technical do
        get 'dashboard/index'
        resources :tools, only: [:index, :show] do
          resources :labs, only: [:index] do
            resources :reportings, only: [:new, :create, :show, :edit, :update, :destroy]
          end
        end
        resources :labs, only: [:show]
        resources :reportings, only: [:index]
        resources :requests
        resources :bookings, only: [:destroy]
      end

      namespace :admin do
        resources :tools do
          resources :documentations, only: [:destroy]
          resources :photos, only: [:destroy]
          resources :bookings, only: [:index]
          resources :labs_tool, only: [:destroy]
        end
        resources :labs do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :technicals, only: [:index, :show] do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :requests, only: [:index, :show, :update, :destroy]
        resources :categories
        resources :lab_technicals, only: [:destroy]
        resources :bookings, only: [:update, :destroy]
        get 'dashboard/index'
        get 'tools/choose/:id(.:format)', :to => 'tools#choose', as: "choose_tool_route"
        get 'labs/assign/:id(.:format)', :to => 'labs#assign', as: "assign_lab_route"
        post 'labs/assign_update/:id/(.:format)', :to => 'labs#assign_update', as: "assign_update_lab_route"
        post 'authorize/:id(.:format)', :to => 'dashboard#authorize', as: "authorize_route"
        post 'confirm/:id(.:format)', :to => 'dashboard#confirm', as: "confirm_route"
        post 'htmlcreate(.:format)', :to => 'categories#htmlcreate', as: "htmlcreate_route"
        delete 'deleteprof/:id(.:format)', :to => 'dashboard#deleteprof', as: "deleteprof_route"
        post 'reportings/dismiss/:id(.:format)', :to => 'reportings#dismiss', as: "dismiss_route"
        post 'reportings/fix/:id(.:format)', :to => 'reportings#fix', as: "fix_route"
        post 'reportings/replace/:id(.:format)', :to => 'reportings#replace', as: "replace_route"
      end

      post 'avaiable/:tool_id(.:format)', :to => 'bookings#avaiable', as: "avaiable_route"
      get 'all_bookings/:id(.:format)', :to => 'tools#all_bookings', as: "all_bookings_route"
      resources :tools, only: [:index, :show] do
        resources :bookings, only: [:new, :create]
        resources :posts, only: [:create, :edit, :update, :destroy]
      end
      resources :categories, only: [:create]
      resources :requests, only: [:new, :create, :index, :show]
      resources :bookings, only: [:index]

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      root to: "home#index"
      #resources :schools
    end
end

app/models/tool.rb
class ToolValidator < ActiveModel::Validator
  def validate(record)

    if record.identifier.present? && record.labs.size > 1
        record.errors[:base] << I18n.t('tools.identifier')
    end
    if record.identifier.present? && record.labs_tools.size == 1
      if record.labs_tools.first.quantity > 1
        record.errors[:base] << I18n.t('tools.identifier')
      end
    end
    if record.identifier.present? && record.labs_tools.size > 1
      record.errors[:base] << I18n.t('tools.identifier')
    end

    if record.labs_tools.size > 1
      lab = []
      for l in record.labs_tools
        lab.push(l.lab_id)
      end

      if lab.uniq.length != lab.length
        record.errors[:base] << I18n.t('tools.labs')
      end
    end

  end
end

class Tool < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  translates :name, :description
  validates :name, presence: true
  validates :identifier, uniqueness: true, :allow_blank => true
  validates :description, presence: true

  has_many :labs_tools, dependent: :destroy
  has_many :labs, through: :labs_tools
  accepts_nested_attributes_for :labs_tools, allow_destroy: true
  has_and_belongs_to_many :categories
  has_many :bookings, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :reportings, dependent: :destroy
  has_many :documentations, dependent: :destroy
  accepts_nested_attributes_for :documentations, allow_destroy: true
  has_many :photos, dependent: :destroy
  validates_each :photos do |tool, attr, value|
   tool.errors.add attr, I18n.t('.tools.photos') if tool.photos.size > 4
  end
  accepts_nested_attributes_for :photos, allow_destroy: true
  before_save :name

#  default_scope -> {order(name: :asc)}
  #default_scope with_translations.order("name ASC")

  validates_with ToolValidator
  paginates_per 12

  def name=(s)
    write_attribute(:name, s.to_s.capitalize)
  end
  def self.with_translated_name(name_string)
  with_translations(I18n.locale).where('tool_translations.name' => name_string)
  end


  private

def self.ransackable_scopes(auth_object = nil)
  %i(with_translated_name)
end

end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Admin::AdminController
  before_action :set_tool, only: [:edit, :destroy, :update, :choose, :show]
  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    @q = Tool.with_translations(I18n.locale).ransack(q_param)
    @tools = @q.result(distinct: true).page(page).per(per_page)

    @categories = Category.all
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      flash[:success]= t('.created')
      redirect_to admin_tool_path(@tool)
    else
      #@tool.errors.full_messages.each do |message|
      #  flash[:danger] = message
      #end
      #redirect_to new_admin_tool_path
      render 'new'
    end
  end

  def show
    @bookings = @tool.bookings.where('end_date >= ? AND confirmed = ?', Time.now, false) #for more info about this job see jobs/admin/checking.rb
    @quantity = 0
    for lab in @tool.labs_tools
      @quantity += lab.quantity
    end
  end

  def choose
  end

  def edit

  end

  def update
    if @tool.update(tool_params)
      flash[:success]= t('.edited')
      redirect_to admin_tool_path(@tool)
    else
      render 'edit'
    end
  end

  def destroy
    if @tool.destroy
      flash[:success]= t('.delete')
      redirect_to admin_tools_path
    else
      redirect_to admin_tools_path
    end
  end

  private

  def set_tool
    @tool = Tool.friendly.find(params[:id])
  end


  def tool_params
    params.require(:tool).permit(:name, :description, :identifier, :fast_booking, {photos_attributes: [:id, :picture, :tool_id, :_destroy]}, {documentations_attributes: [:id, :name, :file, :tool_id, :_destroy]}, {labs_tools_attributes: [:id, :lab_id, :tool_id, :quantity, { lab_ids: []}, :_destroy]}, { lab_ids: []}, { category_ids: []})
  end
end

app/controllers/technical/tools_controller.rb
class Technical::ToolsController < Technical::TechnicalController
  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    lab = params[:lab]
    category = params[:category]

    @q = Tool.with_translations(I18n.locale).ransack(q_param)
    @tools = @q.result(distinct: true).page(page).per(per_page).includes(:categories, :labs)

    @categories = Category.all
    @labs = current_technical.labs
  end

  def show
    @tool = Tool.friendly.find(params[:id])
    @quantity = 0
    for lab in @tool.labs_tools
      @quantity += lab.quantity
    end
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool_bookings, only: [:show, :all_bookings]

  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    lab = params[:lab]
    category = params[:category]
    @q = Tool.with_translations(I18n.locale).ransack(q_param)
    @tools = @q.result(distinct: true).page(page).per(per_page).includes(:categories, :labs)

    @categories = Category.all
    @labs = Lab.all
  end

  def show
    @quantity = 0
    for lab in @tool.labs_tools
      @quantity += lab.quantity
    end
    @posts = @tool.posts
    @booking = @tool.bookings.build
  end

  def all_bookings
  end

  private

  def set_tool_bookings
    @tool = Tool.friendly.find(params[:id])
    @bookings = @tool.bookings.where('end_date >= ? AND confirmed = ?', Time.now, true)
  end

end

app/helpers/admin/tools_helper.rb
module Admin::ToolsHelper
end

app/helpers/technical/tools_helper.rb
module Technical::ToolsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/all_bookings.html.erb
<h1>
  <%= @tool.name %>
</h1>
<hr>
<% if @bookings.present? %>
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-lg-2 col-md-4 col-sm-6">
        <div class="alert alert-secondary" role="alert">
          <h4 class="alert-heading"><%= booking.prof.name + " " + booking.prof.surname %></h4>
          <p> <%= t('tools.show.from') + " " %> <b> <%= booking.start_date.strftime("%d/%m/%y %k:%M").to_s + " " %> </b> <br>
             <%= t('tools.show.to') + " " %> <b> <%= booking.end_date.strftime("%d/%m/%y %k:%M").to_s %> </b> </p>
          <p> <%= t('tools.show.lab') + booking.lab.name %> </p>
          <hr>
          <p class="mb-0"> <%= t('tools.show.quantity') + ": " + booking.quantity.to_s %> </p>
        </div>
      </div>
    <%end%>
  </div>
<% else %>
  <%= t('tools.show.notbooked') %>
<% end %>

app/views/tools/index.html.erb
<h1 class="text-center"> <%= t('shared.menu.tools') %> </h1>
<% if params[:q].present? %>
  <% if params[:q][:categories_name_cont].present? %>
    <h3 class="text-center"> <%= params[:q][:categories_name_cont] %> </h3>
  <% end %>
  <% if params[:q][:labs_name_cont].present? %>
    <h3 class="text-center"> <%= params[:q][:labs_name_cont] %> </h3>
  <% end %>
  <% if params[:q][:translations_name_cont].present? %>
    <h3 class="text-center"> "<%= params[:q][:translations_name_cont] %>" </h3>
  <% end %>
<% end %>

  <div class="row">
    <div class=" col-lg-3 col-md-5">

      <%= link_to t('.newrequest'),  new_request_path, class:"btn btn-outline-primary btn-block" %>
      <br>

      <%= search_form_for @q do |f| %>
        <div class="input-group">
            <%= f.search_field :translations_name_cont, class:"form-control", placeholder: t('.place') %>
            <%= f.submit t('.search'), class:"btn btn-secondary "%>
        </div>
      <% end %>
      <br>

      <div id="accordion" role="tablist">
        <div class="card">
          <div class="card-header" role="tab" id="headingOne">
            <h5 class="mb-0">
              <a data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="false" aria-controls="collapseOne">
                <%= fa_icon('tag') + " " + t('.categories') %>
              </a>
            </h5>
          </div>

          <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
              <% @categories.each do |category| %>
                <%= search_form_for @q do |f| %>
                  <%= f.search_field :categories_name_cont, value: category.name, type:"hidden" %>
                  <td>
                    <%= button_tag type:"submit", class: "btn btn-warning btn-sm btn-block" do %>
                      <%= fa_icon('tag') + " " + category.name %>
                    <% end %>
                  </td>
                <% end %>
                <br>
              <%end%>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" role="tab" id="headingTwo">
            <h5 class="mb-0">
              <a class="collapsed" data-toggle="collapse" href="#collapseTwo" role="button" aria-expanded="false" aria-controls="collapseTwo">
                <%= fa_icon('flask') + " " + t('.labs') %>
              </a>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
              <% @labs.each do |lab| %>
                <%= search_form_for @q do |f| %>
                  <%= f.search_field :labs_name_cont, value: lab.name, type:"hidden" %>
                  <td>
                    <%= button_tag type:"submit", class: "btn btn-primary btn-sm btn-block" do %>
                      <%= fa_icon('flask') + " " + lab.name %>
                    <% end %>
                  </td>
                <% end %>
                <hr>
              <%end%>
            </div>
          </div>
        </div>
      </div>

      <br>
      <div class="LI-profile-badge" width="100%" data-version="v1" data-size="medium" data-locale="<%= I18n.locale %>" data-type="horizontal" data-theme="light" data-vanity="davide-fazio"><a class="LI-simple-link" href='https://it.linkedin.com/in/davide-fazio?trk=profile-badge'>Davide F.</a></div>
      <br>
    </div>

    <div class="col-lg-9 col-md-7">
      <div class="row">
        <% @tools.each do |tool| %>
          <% if tool.name.present? %>
            <div class="col-lg-4 col-sm-6 portfolio-item">
              <div class="card h-100">
                <% if tool.photos.first.present? %>
                  <% if tool.photos.first.picture.standard.present? %>
                    <%= link_to image_tag(tool.photos.first.picture.standard.url, :alt => "toolphoto.jpeg", class:"card-img-top"), tool_path(tool)%>
                  <% else %>
                    <%= link_to image_tag("generico.png", height: 200, :alt => "toolphoto.jpeg", class:"card-img-top"), tool_path(tool)%>
                  <% end %>
                <% else %>
                  <%= link_to image_tag("generico.png", height: 200, :alt => "toolphoto.jpeg", class:"card-img-top"), tool_path(tool)%>
                <% end %>
                <div class="card-body">
                  <h4 class="card-title">
                    <%= tool.name %>
                  </h4>
                  <p class="card-text text-truncate">
                    <%= tool.description %>
                  </p>
                </div>
                <ul class="list-group list-group-flush">
                  <%= link_to fa_icon('eye') + " " + t('.show'), tool_path(tool), class:"list-group-item list-group-item-primary" %>
                </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <ul class="pagination justify-content-center">
    <%= paginate @tools %>
  </ul>