config/routes.rb
Rails.application.routes.draw do

    devise_for :profs, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'profs/omniauth_callbacks'}
    #devise_for :technicals, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'technicals/omniauth_callbacks'}

    scope '(:locale)' do

      devise_for :profs, skip: :omniauth_callbacks, controllers: {
        registrations: 'profs/registrations',
        confirmations: 'profs/confirmations',
      }

      devise_for :technicals, controllers: {
        registrations: 'technicals/registrations',
        confirmations: 'technicals/confirmations',
        sessions: 'technicals/sessions',
      }

      devise_for :admins, controllers: {
        registrations: 'admins/registrations'
      }

      namespace :technical do
        get 'dashboard/index'
        resources :tools, only: [:index, :show] do
          resources :labs, only: [:index] do
            resources :reportings, only: [:new, :create, :show, :edit, :update, :destroy]
          end
        end
        resources :labs, only: [:show]
        resources :reportings, only: [:index]
        resources :requests
        resources :bookings, only: [:destroy]
      end

      namespace :admin do
        resources :tools do
          resources :documentations, only: [:destroy]
          resources :photos, only: [:destroy]
          resources :bookings, only: [:index]
          resources :labs_tool, only: [:destroy]
        end
        resources :labs do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :technicals, only: [:index, :show] do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :requests, only: [:index, :show, :update, :destroy]
        resources :categories
        resources :lab_technicals, only: [:destroy]
        resources :bookings, only: [:update, :destroy]
        get 'dashboard/index'
        get 'tools/choose/:id(.:format)', :to => 'tools#choose', as: "choose_tool_route"
        get 'labs/assign/:id(.:format)', :to => 'labs#assign', as: "assign_lab_route"
        post 'labs/assign_update/:id/(.:format)', :to => 'labs#assign_update', as: "assign_update_lab_route"
        post 'authorize/:id(.:format)', :to => 'dashboard#authorize', as: "authorize_route"
        post 'confirm/:id(.:format)', :to => 'dashboard#confirm', as: "confirm_route"
        post 'htmlcreate(.:format)', :to => 'categories#htmlcreate', as: "htmlcreate_route"
        delete 'deleteprof/:id(.:format)', :to => 'dashboard#deleteprof', as: "deleteprof_route"
        post 'reportings/dismiss/:id(.:format)', :to => 'reportings#dismiss', as: "dismiss_route"
        post 'reportings/fix/:id(.:format)', :to => 'reportings#fix', as: "fix_route"
        post 'reportings/replace/:id(.:format)', :to => 'reportings#replace', as: "replace_route"
      end

      post 'avaiable/:tool_id(.:format)', :to => 'bookings#avaiable', as: "avaiable_route"
      get 'all_bookings/:id(.:format)', :to => 'tools#all_bookings', as: "all_bookings_route"
      resources :tools, only: [:index, :show] do
        resources :bookings, only: [:new, :create]
        resources :posts, only: [:create, :edit, :update, :destroy]
      end
      resources :categories, only: [:create]
      resources :requests, only: [:new, :create, :index, :show]
      resources :bookings, only: [:index]

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      root to: "home#index"
      #resources :schools
    end
end

app/models/lab.rb
class Lab < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true, uniqueness: true
  validates :subject, presence: true
  has_many :labs_tools
  has_many :tools, through: :labs_tools
  has_many :lab_technicals
  has_many :technicals, through: :lab_technicals
  has_many :bookings, dependent: :destroy
  has_many :reportings, dependent: :destroy
  accepts_nested_attributes_for :labs_tools

  paginates_per 24
  before_save :name
  before_save :subject
  def name=(s)
    write_attribute(:name, s.to_s.capitalize)
  end
  def subject=(s)
    write_attribute(:subject, s.to_s.capitalize)
  end
end

app/controllers/admin/labs_controller.rb
class Admin::LabsController < Admin::AdminController
  before_action :set_lab, only: [:show, :edit, :update, :destroy, :assign, :assign_update]

  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    @q = Lab.order(:id).ransack(q_param)
    @labs = @q.result(distinct: true).page(page).per(per_page)
  end

  def new
    @lab = Lab.new
  end

  def create
    @lab = Lab.new(lab_params)
    if @lab.save
      flash[:success]= t('.created')
      redirect_to admin_labs_path
    else
      render 'new'
    end
  end

  def show
  end

  def assign

    @lab_tool = LabsTool.new
  end

  def edit_tool
  end

  def destroy_tool
  end

  def assign_update
      @lab_tool = LabsTool.new(labs_tool_params)
      if @lab_tool.save
        redirect_to admin_lab_path
      else
        render 'assign_tool'
      end
  end


  def edit

  end

  def update
    if @lab.update(lab_params)
      flash[:success]= t('.edited')
      redirect_to admin_labs_path
    else
      render 'edit'
    end
  end

  def destroy
    if @lab.destroy
      flash[:success]= t('.delete')
      redirect_to admin_labs_path
    else
      redirect_to admin_labs_path
    end
  end

  private

  def set_lab
    @lab = Lab.friendly.find(params[:id])
  end

  def lab_params
    params.require(:lab).permit(:name, :subject, { tool_ids:[]})
  end

  def labs_tool_params
    params.require(:labs_tool).permit(:tool_id, :lab_id, :quantity)
  end
end

app/controllers/technical/labs_controller.rb
class Technical::LabsController < Technical::TechnicalController

  def index
    @tool = Tool.friendly.find(params[:tool_id])
    @labs = @tool.labs
  end

  def show
    @lab = Lab.friendly.find(params[:id])
    if current_technical.labs.include?(@lab)
      if current_technical.lab_technicals.where("lab_id=?", @lab.id).first.end_date == nil
        @bookings = @lab.bookings.where("end_date > ? AND confirmed = ?", Time.now, true)
      elsif current_technical.lab_technicals.where("lab_id=?", @lab.id).first.end_date < Time.now
        redirect_back(fallback_location:  technical_dashboard_index_path)
      else
        @bookings = @lab.bookings.where("end_date > ? AND confirmed = ?", Time.now, true)
      end
    else
      redirect_back(fallback_location:  technical_dashboard_index_path)
    end
  end

end

app/helpers/admin/labs_helper.rb
module Admin::LabsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/technical/labs_helper.rb
module Technical::LabsHelper
end

app/views/admin/labs/_form.html.erb
<%= form_for ([:admin, @lab]) do |t|  %>

  <% if @lab.errors.any? %>
    <div id="error_explanation">
      <% @lab.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="form-group" >
        <%=t.label t('.name')%>
        <%=t.text_field :name, class:"form-control"%>
      </div>
    </div>
    <div class="col-md-6 col-sm-6">
      <div class="form-group">
        <%=t.label t('.subject')%>
        <%=t.text_field :subject, class:"form-control"%>
      </div>
    </div>
  </div>

  <%= t.submit class:"btn btn-primary btn-block"%>

<% end %>

app/views/admin/labs/assign.html.erb
<!-- a tool can be assigned to one or more laboratories,
     but it can not be assigned to a number of laboratories greater than the available quantity.
     For example: two backers can not be in three laboratories. -->
<%
all_tool = []
  for tool in Tool.all
    if (tool.labs.include?(@lab) == false) && ( (tool.identifier.present? == false) || (tool.identifier.present? && tool.labs.size == 0) )
      all_tool.push(tool)
    end
  end
%>
<%= form_for @lab_tool, url: admin_assign_update_lab_route_path do |t| %>
  <%= t.hidden_field(:lab_id, :value => @lab.id) %>
  <% for tool in all_tool %>
    <%= t.radio_button :tool_id , tool.id, checked: false %>
    <input type="text" class="form-control" aria-label="Text input with checkbox" value="<%= tool.name %>" readonly>
  <% end %>
  <%= t.label "Quantità" %>
  <%= t.text_field :quantity %>
  <%= t.submit "Assegna" %>
<% end %>
<hr>
<!--
<div class="row">
  <%# for tool in all_tool %>
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
        <%# if tool.photos.first.picture.standard.present? %>
          <%# link_to image_tag(tool.photos.first.picture.standard.url, :alt => "toolphoto.jpeg", class:"card-img-top"), tool_path(tool)%>
        <%# else %>
          <%# link_to image_tag("generico.png", height: 200, :alt => "toolphoto.jpeg", class:"card-img-top"), tool_path(tool)%>
        <%# end %>
          <div class="card-body">
            <h4 class="card-title">
              <%# tool.name %>
            </h4>

          </div>
          <ul class="list-group list-group-flush">
            <%# link_to "Assegna", tool_path(tool), class:"list-group-item list-group-item-primary" %>
          </ul>
        </div>
      </div>
  <%# end %>
</div>
-->

app/views/admin/labs/index.html.erb
<h1> <%= t('admin.shared.menu.labs') %> </h1>
<hr>

<%= link_to t('.new'), new_admin_lab_path, class:"btn btn-primary btn-block" %>
<hr>

<div class="row">
  <% @labs.each do |lab| %>
    <div class="col-lg-3 col-sm-4 portfolio-item">
      <div class="card h-100">
        <div class="card-header">
          <%= lab.name %> <%= link_to fa_icon('eye'), admin_lab_path(lab), class:"btn btn-primary" %>
          <%= link_to fa_icon('pencil'), edit_admin_lab_path(lab), class:"btn btn-warning " %>
          <%= link_to fa_icon('trash'), admin_lab_path(lab), method: :delete, data: {confirm: t('.confirm')}, class:"btn btn-danger" %>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <%= lab.subject %> </h5>
           <p class="card-text"> <%= t('.labtools') %> <span class="badge badge-primary badge-pill"> <%=lab.tools.size %> </span> </p>
          <%# link_to fa_icon('wrench') + " " + fa_icon('plus'), admin_assign_lab_route_path(lab), class:"btn btn-success", toggle:"tooltip", placement:"top", title: t('.assign')%>
          <%= link_to fa_icon('users') + " " + fa_icon('plus') + " " + t('.assigntech'), new_admin_lab_lab_technical_path(lab), class:"btn btn-info", toggle:"tooltip", placement:"top", title: t('.assigntech') %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<hr>

<div class="paginate-container">
  <%= paginate @labs %>
</div>

app/views/admin/labs/show.html.erb
<h1> <%= @lab.name %> </h1>
<hr>

<div class="row">
  <% @lab.lab_technicals.each do |relation| %>
    <div class="col-lg-3 col-sm-4 portfolio-item">
      <div class="card h-100">
        <div class= "card-header">
          <%= relation.technical.name + " " + relation.technical.surname %>
        </div>
        <div class="card-body">
          <% if relation.end_date.present? %>
            <%= t('tools.show.from') + " " + relation.start_date.strftime("%d/%m/%y %k:%M").to_s%>
            <br>
            <%= t('tools.show.to') + " " + relation.end_date.strftime("%d/%m/%y %k:%M").to_s%>
          <% else %>
            <%= t('tools.show.from') + " " + relation.start_date.strftime("%d/%m/%y %k:%M").to_s%>
            <br>
            <b> <%= t('.present') %> </b>
          <% end %>
          <%= link_to fa_icon('trash'), admin_lab_technical_path(relation), method: :delete, data: {confirm: t('admin.tools.index.confirm')}, class:"btn btn-sm btn-danger"%>
          <%= link_to fa_icon('pencil'), edit_admin_lab_lab_technical_path(@lab, relation), class:"btn btn-warning btn-sm" %>
        </div>
      </div>
    </div>
  <% end %>
</div>